info:
  app_name: 网关服务
  author: 牙子
  email: zyr@outlook.com
server:
  port: 8040
spring:
  application:
    name: gateway
  http:
    encoding:
      #解决读取文件乱码的问题
      force: true
  profiles:
    #启动的默认配置
    active: common, prod
  cloud:
    #参考gateway配置文档，尤其是谓词和过滤器，官网是最全的
    #https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.1.0.RELEASE/single/spring-cloud-gateway.html#gateway-starter
    gateway:
      discovery:
        locator:
          #让gateway自动通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: wechat_route
          uri: lb://wechat-center
          predicates:
            - Path=/wechat/**
            #自定义谓词工厂
            - TimeBetween=上午00:00, 下午11:59
          filters:
            - PreLog=paramKey,paramValue
            - PostLog=paramKey,paramValue
            - StripPrefix=1
        - id: account_route
          uri: lb://account-center
          predicates:
            - Path=/account/**
            #自定义谓词工厂
            - TimeBetween=上午00:00, 下午11:59
          filters:
            - PreLog=paramKey,paramValue
            - PostLog=paramKey,paramValue
            - StripPrefix=1
      default-filters:
        - AddRequestHeader=X-Request-Author, zyr
        - PreLog=paramKey,paramValue
        - PostLog=paramKey,paramValue
#gateway配置
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug